fix: log full API response payload on 4xx/5xx errors
requests.raise_for_status() only provides a generic error reason in the
traceback when you get hit with a 422, for example:

```
File "/usr/local/lib/python3.12/site-packages/requests/models.py", line
1024, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity
for url: https://app.hex.tech/api/v1/project/uuid-here/run
```

The full response payload should also be logged so that users can easily
debug the reason why an API request failed:

```
{"reason":"Slack notifications cannot be sent. The user has not enabled
notifications for Slack. Please enable it in Notifications
settings.","traceId":"xxxx"}
```